// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "my_ip_hls.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic my_ip_hls::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic my_ip_hls::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> my_ip_hls::ap_ST_iter0_fsm_state1 = "1";
const sc_lv<2> my_ip_hls::ap_ST_iter1_fsm_state2 = "10";
const sc_lv<2> my_ip_hls::ap_ST_iter2_fsm_state3 = "10";
const sc_lv<2> my_ip_hls::ap_ST_iter1_fsm_state0 = "1";
const sc_lv<2> my_ip_hls::ap_ST_iter2_fsm_state0 = "1";
const bool my_ip_hls::ap_const_boolean_1 = true;
const sc_lv<1> my_ip_hls::ap_const_lv1_0 = "0";
const sc_lv<1> my_ip_hls::ap_const_lv1_1 = "1";
const sc_lv<2> my_ip_hls::ap_const_lv2_0 = "00";
const sc_lv<2> my_ip_hls::ap_const_lv2_2 = "10";
const sc_lv<2> my_ip_hls::ap_const_lv2_3 = "11";
const sc_lv<2> my_ip_hls::ap_const_lv2_1 = "1";
const sc_lv<32> my_ip_hls::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> my_ip_hls::ap_const_lv32_1 = "1";
const bool my_ip_hls::ap_const_boolean_0 = false;

my_ip_hls::my_ip_hls(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_MasterOut_TDATA);
    sensitive << ( MasterOut_V_data_V_1_data_out );

    SC_METHOD(thread_MasterOut_TDATA_blk_n);
    sensitive << ( MasterOut_V_data_V_1_state );
    sensitive << ( ap_CS_iter1_fsm_state2 );
    sensitive << ( ap_CS_iter2_fsm_state3 );
    sensitive << ( tmp_reg_89 );
    sensitive << ( ap_reg_pp0_iter1_tmp_reg_89 );

    SC_METHOD(thread_MasterOut_TLAST);
    sensitive << ( MasterOut_V_last_V_1_data_out );

    SC_METHOD(thread_MasterOut_TSTRB);
    sensitive << ( MasterOut_V_strb_V_1_data_out );

    SC_METHOD(thread_MasterOut_TVALID);
    sensitive << ( MasterOut_V_last_V_1_state );

    SC_METHOD(thread_MasterOut_V_data_V_1_ack_in);
    sensitive << ( MasterOut_V_data_V_1_state );

    SC_METHOD(thread_MasterOut_V_data_V_1_ack_out);
    sensitive << ( MasterOut_TREADY );

    SC_METHOD(thread_MasterOut_V_data_V_1_data_out);
    sensitive << ( MasterOut_V_data_V_1_payload_A );
    sensitive << ( MasterOut_V_data_V_1_payload_B );
    sensitive << ( MasterOut_V_data_V_1_sel );

    SC_METHOD(thread_MasterOut_V_data_V_1_load_A);
    sensitive << ( MasterOut_V_data_V_1_sel_wr );
    sensitive << ( MasterOut_V_data_V_1_state_cmp_full );

    SC_METHOD(thread_MasterOut_V_data_V_1_load_B);
    sensitive << ( MasterOut_V_data_V_1_sel_wr );
    sensitive << ( MasterOut_V_data_V_1_state_cmp_full );

    SC_METHOD(thread_MasterOut_V_data_V_1_sel);
    sensitive << ( MasterOut_V_data_V_1_sel_rd );

    SC_METHOD(thread_MasterOut_V_data_V_1_state_cmp_full);
    sensitive << ( MasterOut_V_data_V_1_state );

    SC_METHOD(thread_MasterOut_V_data_V_1_vld_in);
    sensitive << ( MasterOut_V_data_V_1_ack_in );
    sensitive << ( MasterOut_V_strb_V_1_ack_in );
    sensitive << ( MasterOut_V_last_V_1_ack_in );
    sensitive << ( ap_CS_iter1_fsm_state2 );
    sensitive << ( ap_CS_iter2_fsm_state3 );
    sensitive << ( tmp_reg_89 );
    sensitive << ( ap_block_state2_io );
    sensitive << ( ap_block_state3_io );

    SC_METHOD(thread_MasterOut_V_data_V_1_vld_out);
    sensitive << ( MasterOut_V_data_V_1_state );

    SC_METHOD(thread_MasterOut_V_last_V_1_ack_in);
    sensitive << ( MasterOut_V_last_V_1_state );

    SC_METHOD(thread_MasterOut_V_last_V_1_ack_out);
    sensitive << ( MasterOut_TREADY );

    SC_METHOD(thread_MasterOut_V_last_V_1_data_out);
    sensitive << ( MasterOut_V_last_V_1_payload_A );
    sensitive << ( MasterOut_V_last_V_1_payload_B );
    sensitive << ( MasterOut_V_last_V_1_sel );

    SC_METHOD(thread_MasterOut_V_last_V_1_load_A);
    sensitive << ( MasterOut_V_last_V_1_sel_wr );
    sensitive << ( MasterOut_V_last_V_1_state_cmp_full );

    SC_METHOD(thread_MasterOut_V_last_V_1_load_B);
    sensitive << ( MasterOut_V_last_V_1_sel_wr );
    sensitive << ( MasterOut_V_last_V_1_state_cmp_full );

    SC_METHOD(thread_MasterOut_V_last_V_1_sel);
    sensitive << ( MasterOut_V_last_V_1_sel_rd );

    SC_METHOD(thread_MasterOut_V_last_V_1_state_cmp_full);
    sensitive << ( MasterOut_V_last_V_1_state );

    SC_METHOD(thread_MasterOut_V_last_V_1_vld_in);
    sensitive << ( MasterOut_V_data_V_1_ack_in );
    sensitive << ( MasterOut_V_strb_V_1_ack_in );
    sensitive << ( MasterOut_V_last_V_1_ack_in );
    sensitive << ( ap_CS_iter1_fsm_state2 );
    sensitive << ( ap_CS_iter2_fsm_state3 );
    sensitive << ( tmp_reg_89 );
    sensitive << ( ap_block_state2_io );
    sensitive << ( ap_block_state3_io );

    SC_METHOD(thread_MasterOut_V_last_V_1_vld_out);
    sensitive << ( MasterOut_V_last_V_1_state );

    SC_METHOD(thread_MasterOut_V_strb_V_1_ack_in);
    sensitive << ( MasterOut_V_strb_V_1_state );

    SC_METHOD(thread_MasterOut_V_strb_V_1_ack_out);
    sensitive << ( MasterOut_TREADY );

    SC_METHOD(thread_MasterOut_V_strb_V_1_data_out);
    sensitive << ( MasterOut_V_strb_V_1_payload_A );
    sensitive << ( MasterOut_V_strb_V_1_payload_B );
    sensitive << ( MasterOut_V_strb_V_1_sel );

    SC_METHOD(thread_MasterOut_V_strb_V_1_load_A);
    sensitive << ( MasterOut_V_strb_V_1_sel_wr );
    sensitive << ( MasterOut_V_strb_V_1_state_cmp_full );

    SC_METHOD(thread_MasterOut_V_strb_V_1_load_B);
    sensitive << ( MasterOut_V_strb_V_1_sel_wr );
    sensitive << ( MasterOut_V_strb_V_1_state_cmp_full );

    SC_METHOD(thread_MasterOut_V_strb_V_1_sel);
    sensitive << ( MasterOut_V_strb_V_1_sel_rd );

    SC_METHOD(thread_MasterOut_V_strb_V_1_state_cmp_full);
    sensitive << ( MasterOut_V_strb_V_1_state );

    SC_METHOD(thread_MasterOut_V_strb_V_1_vld_in);
    sensitive << ( MasterOut_V_data_V_1_ack_in );
    sensitive << ( MasterOut_V_strb_V_1_ack_in );
    sensitive << ( MasterOut_V_last_V_1_ack_in );
    sensitive << ( ap_CS_iter1_fsm_state2 );
    sensitive << ( ap_CS_iter2_fsm_state3 );
    sensitive << ( tmp_reg_89 );
    sensitive << ( ap_block_state2_io );
    sensitive << ( ap_block_state3_io );

    SC_METHOD(thread_MasterOut_V_strb_V_1_vld_out);
    sensitive << ( MasterOut_V_strb_V_1_state );

    SC_METHOD(thread_ap_CS_iter0_fsm_state1);
    sensitive << ( ap_CS_iter0_fsm );

    SC_METHOD(thread_ap_CS_iter1_fsm_state2);
    sensitive << ( ap_CS_iter1_fsm );

    SC_METHOD(thread_ap_CS_iter2_fsm_state3);
    sensitive << ( ap_CS_iter2_fsm );

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);
    sensitive << ( slaveIn_TVALID );
    sensitive << ( tmp_nbreadreq_fu_42_p5 );

    SC_METHOD(thread_ap_block_state2_io);
    sensitive << ( MasterOut_V_data_V_1_ack_in );
    sensitive << ( tmp_reg_89 );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state3_io);
    sensitive << ( MasterOut_V_data_V_1_ack_in );
    sensitive << ( ap_reg_pp0_iter1_tmp_reg_89 );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2);
    sensitive << ( MasterOut_V_data_V_1_ack_in );
    sensitive << ( MasterOut_V_strb_V_1_ack_in );
    sensitive << ( MasterOut_V_last_V_1_ack_in );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_slaveIn_TDATA_blk_n);
    sensitive << ( slaveIn_TVALID );
    sensitive << ( ap_CS_iter0_fsm_state1 );
    sensitive << ( tmp_nbreadreq_fu_42_p5 );

    SC_METHOD(thread_slaveIn_TREADY);
    sensitive << ( slaveIn_TVALID );
    sensitive << ( MasterOut_V_data_V_1_ack_in );
    sensitive << ( MasterOut_V_strb_V_1_ack_in );
    sensitive << ( MasterOut_V_last_V_1_ack_in );
    sensitive << ( ap_CS_iter0_fsm_state1 );
    sensitive << ( ap_CS_iter1_fsm_state2 );
    sensitive << ( ap_CS_iter2_fsm_state3 );
    sensitive << ( tmp_nbreadreq_fu_42_p5 );
    sensitive << ( ap_block_state2_io );
    sensitive << ( ap_block_state3_io );

    SC_METHOD(thread_tmp_nbreadreq_fu_42_p5);
    sensitive << ( slaveIn_TVALID );

    SC_METHOD(thread_ap_NS_iter0_fsm);
    sensitive << ( slaveIn_TVALID );
    sensitive << ( MasterOut_V_data_V_1_ack_in );
    sensitive << ( MasterOut_V_strb_V_1_ack_in );
    sensitive << ( MasterOut_V_last_V_1_ack_in );
    sensitive << ( ap_CS_iter0_fsm );
    sensitive << ( ap_CS_iter1_fsm_state2 );
    sensitive << ( ap_CS_iter2_fsm_state3 );
    sensitive << ( tmp_nbreadreq_fu_42_p5 );
    sensitive << ( ap_block_state2_io );
    sensitive << ( ap_block_state3_io );

    SC_METHOD(thread_ap_NS_iter1_fsm);
    sensitive << ( slaveIn_TVALID );
    sensitive << ( MasterOut_V_data_V_1_ack_in );
    sensitive << ( MasterOut_V_strb_V_1_ack_in );
    sensitive << ( MasterOut_V_last_V_1_ack_in );
    sensitive << ( ap_CS_iter0_fsm_state1 );
    sensitive << ( ap_CS_iter1_fsm );
    sensitive << ( ap_CS_iter1_fsm_state2 );
    sensitive << ( ap_CS_iter2_fsm_state3 );
    sensitive << ( tmp_nbreadreq_fu_42_p5 );
    sensitive << ( ap_block_state2_io );
    sensitive << ( ap_block_state3_io );

    SC_METHOD(thread_ap_NS_iter2_fsm);
    sensitive << ( MasterOut_V_data_V_1_ack_in );
    sensitive << ( MasterOut_V_strb_V_1_ack_in );
    sensitive << ( MasterOut_V_last_V_1_ack_in );
    sensitive << ( ap_CS_iter1_fsm_state2 );
    sensitive << ( ap_CS_iter2_fsm );
    sensitive << ( ap_CS_iter2_fsm_state3 );
    sensitive << ( ap_block_state2_io );
    sensitive << ( ap_block_state3_io );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    MasterOut_V_data_V_1_sel_rd = SC_LOGIC_0;
    MasterOut_V_data_V_1_sel_wr = SC_LOGIC_0;
    MasterOut_V_data_V_1_state = "00";
    MasterOut_V_strb_V_1_sel_rd = SC_LOGIC_0;
    MasterOut_V_strb_V_1_sel_wr = SC_LOGIC_0;
    MasterOut_V_strb_V_1_state = "00";
    MasterOut_V_last_V_1_sel_rd = SC_LOGIC_0;
    MasterOut_V_last_V_1_sel_wr = SC_LOGIC_0;
    MasterOut_V_last_V_1_state = "00";
    ap_CS_iter0_fsm = "1";
    ap_CS_iter1_fsm = "01";
    ap_CS_iter2_fsm = "01";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "my_ip_hls_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, slaveIn_TDATA, "(port)slaveIn_TDATA");
    sc_trace(mVcdFile, slaveIn_TVALID, "(port)slaveIn_TVALID");
    sc_trace(mVcdFile, slaveIn_TREADY, "(port)slaveIn_TREADY");
    sc_trace(mVcdFile, slaveIn_TSTRB, "(port)slaveIn_TSTRB");
    sc_trace(mVcdFile, slaveIn_TLAST, "(port)slaveIn_TLAST");
    sc_trace(mVcdFile, MasterOut_TDATA, "(port)MasterOut_TDATA");
    sc_trace(mVcdFile, MasterOut_TVALID, "(port)MasterOut_TVALID");
    sc_trace(mVcdFile, MasterOut_TREADY, "(port)MasterOut_TREADY");
    sc_trace(mVcdFile, MasterOut_TSTRB, "(port)MasterOut_TSTRB");
    sc_trace(mVcdFile, MasterOut_TLAST, "(port)MasterOut_TLAST");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, MasterOut_V_data_V_1_data_out, "MasterOut_V_data_V_1_data_out");
    sc_trace(mVcdFile, MasterOut_V_data_V_1_vld_in, "MasterOut_V_data_V_1_vld_in");
    sc_trace(mVcdFile, MasterOut_V_data_V_1_vld_out, "MasterOut_V_data_V_1_vld_out");
    sc_trace(mVcdFile, MasterOut_V_data_V_1_ack_in, "MasterOut_V_data_V_1_ack_in");
    sc_trace(mVcdFile, MasterOut_V_data_V_1_ack_out, "MasterOut_V_data_V_1_ack_out");
    sc_trace(mVcdFile, MasterOut_V_data_V_1_payload_A, "MasterOut_V_data_V_1_payload_A");
    sc_trace(mVcdFile, MasterOut_V_data_V_1_payload_B, "MasterOut_V_data_V_1_payload_B");
    sc_trace(mVcdFile, MasterOut_V_data_V_1_sel_rd, "MasterOut_V_data_V_1_sel_rd");
    sc_trace(mVcdFile, MasterOut_V_data_V_1_sel_wr, "MasterOut_V_data_V_1_sel_wr");
    sc_trace(mVcdFile, MasterOut_V_data_V_1_sel, "MasterOut_V_data_V_1_sel");
    sc_trace(mVcdFile, MasterOut_V_data_V_1_load_A, "MasterOut_V_data_V_1_load_A");
    sc_trace(mVcdFile, MasterOut_V_data_V_1_load_B, "MasterOut_V_data_V_1_load_B");
    sc_trace(mVcdFile, MasterOut_V_data_V_1_state, "MasterOut_V_data_V_1_state");
    sc_trace(mVcdFile, MasterOut_V_data_V_1_state_cmp_full, "MasterOut_V_data_V_1_state_cmp_full");
    sc_trace(mVcdFile, MasterOut_V_strb_V_1_data_out, "MasterOut_V_strb_V_1_data_out");
    sc_trace(mVcdFile, MasterOut_V_strb_V_1_vld_in, "MasterOut_V_strb_V_1_vld_in");
    sc_trace(mVcdFile, MasterOut_V_strb_V_1_vld_out, "MasterOut_V_strb_V_1_vld_out");
    sc_trace(mVcdFile, MasterOut_V_strb_V_1_ack_in, "MasterOut_V_strb_V_1_ack_in");
    sc_trace(mVcdFile, MasterOut_V_strb_V_1_ack_out, "MasterOut_V_strb_V_1_ack_out");
    sc_trace(mVcdFile, MasterOut_V_strb_V_1_payload_A, "MasterOut_V_strb_V_1_payload_A");
    sc_trace(mVcdFile, MasterOut_V_strb_V_1_payload_B, "MasterOut_V_strb_V_1_payload_B");
    sc_trace(mVcdFile, MasterOut_V_strb_V_1_sel_rd, "MasterOut_V_strb_V_1_sel_rd");
    sc_trace(mVcdFile, MasterOut_V_strb_V_1_sel_wr, "MasterOut_V_strb_V_1_sel_wr");
    sc_trace(mVcdFile, MasterOut_V_strb_V_1_sel, "MasterOut_V_strb_V_1_sel");
    sc_trace(mVcdFile, MasterOut_V_strb_V_1_load_A, "MasterOut_V_strb_V_1_load_A");
    sc_trace(mVcdFile, MasterOut_V_strb_V_1_load_B, "MasterOut_V_strb_V_1_load_B");
    sc_trace(mVcdFile, MasterOut_V_strb_V_1_state, "MasterOut_V_strb_V_1_state");
    sc_trace(mVcdFile, MasterOut_V_strb_V_1_state_cmp_full, "MasterOut_V_strb_V_1_state_cmp_full");
    sc_trace(mVcdFile, MasterOut_V_last_V_1_data_out, "MasterOut_V_last_V_1_data_out");
    sc_trace(mVcdFile, MasterOut_V_last_V_1_vld_in, "MasterOut_V_last_V_1_vld_in");
    sc_trace(mVcdFile, MasterOut_V_last_V_1_vld_out, "MasterOut_V_last_V_1_vld_out");
    sc_trace(mVcdFile, MasterOut_V_last_V_1_ack_in, "MasterOut_V_last_V_1_ack_in");
    sc_trace(mVcdFile, MasterOut_V_last_V_1_ack_out, "MasterOut_V_last_V_1_ack_out");
    sc_trace(mVcdFile, MasterOut_V_last_V_1_payload_A, "MasterOut_V_last_V_1_payload_A");
    sc_trace(mVcdFile, MasterOut_V_last_V_1_payload_B, "MasterOut_V_last_V_1_payload_B");
    sc_trace(mVcdFile, MasterOut_V_last_V_1_sel_rd, "MasterOut_V_last_V_1_sel_rd");
    sc_trace(mVcdFile, MasterOut_V_last_V_1_sel_wr, "MasterOut_V_last_V_1_sel_wr");
    sc_trace(mVcdFile, MasterOut_V_last_V_1_sel, "MasterOut_V_last_V_1_sel");
    sc_trace(mVcdFile, MasterOut_V_last_V_1_load_A, "MasterOut_V_last_V_1_load_A");
    sc_trace(mVcdFile, MasterOut_V_last_V_1_load_B, "MasterOut_V_last_V_1_load_B");
    sc_trace(mVcdFile, MasterOut_V_last_V_1_state, "MasterOut_V_last_V_1_state");
    sc_trace(mVcdFile, MasterOut_V_last_V_1_state_cmp_full, "MasterOut_V_last_V_1_state_cmp_full");
    sc_trace(mVcdFile, slaveIn_TDATA_blk_n, "slaveIn_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_iter0_fsm, "ap_CS_iter0_fsm");
    sc_trace(mVcdFile, ap_CS_iter0_fsm_state1, "ap_CS_iter0_fsm_state1");
    sc_trace(mVcdFile, ap_CS_iter1_fsm, "ap_CS_iter1_fsm");
    sc_trace(mVcdFile, ap_CS_iter1_fsm_state2, "ap_CS_iter1_fsm_state2");
    sc_trace(mVcdFile, ap_CS_iter2_fsm, "ap_CS_iter2_fsm");
    sc_trace(mVcdFile, ap_CS_iter2_fsm_state3, "ap_CS_iter2_fsm_state3");
    sc_trace(mVcdFile, tmp_nbreadreq_fu_42_p5, "tmp_nbreadreq_fu_42_p5");
    sc_trace(mVcdFile, MasterOut_TDATA_blk_n, "MasterOut_TDATA_blk_n");
    sc_trace(mVcdFile, tmp_reg_89, "tmp_reg_89");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_tmp_reg_89, "ap_reg_pp0_iter1_tmp_reg_89");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state2_io, "ap_block_state2_io");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2, "ap_block_state3_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state3_io, "ap_block_state3_io");
    sc_trace(mVcdFile, tmp_data_V_reg_93, "tmp_data_V_reg_93");
    sc_trace(mVcdFile, tmp_strb_V_reg_98, "tmp_strb_V_reg_98");
    sc_trace(mVcdFile, tmp_last_V_reg_103, "tmp_last_V_reg_103");
    sc_trace(mVcdFile, ap_NS_iter0_fsm, "ap_NS_iter0_fsm");
    sc_trace(mVcdFile, ap_NS_iter1_fsm, "ap_NS_iter1_fsm");
    sc_trace(mVcdFile, ap_NS_iter2_fsm, "ap_NS_iter2_fsm");
#endif

    }
    mHdltvinHandle.open("my_ip_hls.hdltvin.dat");
    mHdltvoutHandle.open("my_ip_hls.hdltvout.dat");
}

my_ip_hls::~my_ip_hls() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void my_ip_hls::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        MasterOut_V_data_V_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_data_V_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_data_V_1_vld_out.read()))) {
            MasterOut_V_data_V_1_sel_rd =  (sc_logic) (~MasterOut_V_data_V_1_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        MasterOut_V_data_V_1_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_data_V_1_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_data_V_1_ack_in.read()))) {
            MasterOut_V_data_V_1_sel_wr =  (sc_logic) (~MasterOut_V_data_V_1_sel_wr.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        MasterOut_V_data_V_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_data_V_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_data_V_1_ack_out.read()) && 
              esl_seteq<1,2,2>(MasterOut_V_data_V_1_state.read(), ap_const_lv2_3)) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_data_V_1_vld_in.read()) && 
              esl_seteq<1,2,2>(MasterOut_V_data_V_1_state.read(), ap_const_lv2_2)))) {
            MasterOut_V_data_V_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_data_V_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(MasterOut_V_data_V_1_state.read(), ap_const_lv2_3)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(MasterOut_V_data_V_1_state.read(), ap_const_lv2_1)))) {
            MasterOut_V_data_V_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_data_V_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(MasterOut_V_data_V_1_state.read(), ap_const_lv2_2)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(MasterOut_V_data_V_1_state.read(), ap_const_lv2_1)) || 
                    (esl_seteq<1,2,2>(MasterOut_V_data_V_1_state.read(), ap_const_lv2_3) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_data_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_data_V_1_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_data_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_data_V_1_ack_out.read()))))) {
            MasterOut_V_data_V_1_state = ap_const_lv2_3;
        } else {
            MasterOut_V_data_V_1_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        MasterOut_V_last_V_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_last_V_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_last_V_1_vld_out.read()))) {
            MasterOut_V_last_V_1_sel_rd =  (sc_logic) (~MasterOut_V_last_V_1_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        MasterOut_V_last_V_1_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_last_V_1_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_last_V_1_ack_in.read()))) {
            MasterOut_V_last_V_1_sel_wr =  (sc_logic) (~MasterOut_V_last_V_1_sel_wr.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        MasterOut_V_last_V_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_last_V_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_last_V_1_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, MasterOut_V_last_V_1_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_last_V_1_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, MasterOut_V_last_V_1_state.read())))) {
            MasterOut_V_last_V_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_last_V_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_last_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, MasterOut_V_last_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_last_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, MasterOut_V_last_V_1_state.read())))) {
            MasterOut_V_last_V_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_last_V_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, MasterOut_V_last_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_last_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, MasterOut_V_last_V_1_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, MasterOut_V_last_V_1_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_last_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_last_V_1_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_last_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_last_V_1_ack_out.read()))))) {
            MasterOut_V_last_V_1_state = ap_const_lv2_3;
        } else {
            MasterOut_V_last_V_1_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        MasterOut_V_strb_V_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_strb_V_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_strb_V_1_vld_out.read()))) {
            MasterOut_V_strb_V_1_sel_rd =  (sc_logic) (~MasterOut_V_strb_V_1_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        MasterOut_V_strb_V_1_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_strb_V_1_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_strb_V_1_ack_in.read()))) {
            MasterOut_V_strb_V_1_sel_wr =  (sc_logic) (~MasterOut_V_strb_V_1_sel_wr.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        MasterOut_V_strb_V_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_strb_V_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_strb_V_1_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, MasterOut_V_strb_V_1_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_strb_V_1_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, MasterOut_V_strb_V_1_state.read())))) {
            MasterOut_V_strb_V_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_strb_V_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_strb_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, MasterOut_V_strb_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_strb_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, MasterOut_V_strb_V_1_state.read())))) {
            MasterOut_V_strb_V_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_strb_V_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, MasterOut_V_strb_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_strb_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, MasterOut_V_strb_V_1_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, MasterOut_V_strb_V_1_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_strb_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_strb_V_1_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_strb_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_strb_V_1_ack_out.read()))))) {
            MasterOut_V_strb_V_1_state = ap_const_lv2_3;
        } else {
            MasterOut_V_strb_V_1_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_iter0_fsm = ap_ST_iter0_fsm_state1;
    } else {
        ap_CS_iter0_fsm = ap_NS_iter0_fsm.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_iter1_fsm = ap_ST_iter1_fsm_state0;
    } else {
        ap_CS_iter1_fsm = ap_NS_iter1_fsm.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_iter2_fsm = ap_ST_iter2_fsm_state0;
    } else {
        ap_CS_iter2_fsm = ap_NS_iter2_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_data_V_1_load_A.read())) {
        MasterOut_V_data_V_1_payload_A = tmp_data_V_reg_93.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_data_V_1_load_B.read())) {
        MasterOut_V_data_V_1_payload_B = tmp_data_V_reg_93.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_last_V_1_load_A.read())) {
        MasterOut_V_last_V_1_payload_A = tmp_last_V_reg_103.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_last_V_1_load_B.read())) {
        MasterOut_V_last_V_1_payload_B = tmp_last_V_reg_103.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_strb_V_1_load_A.read())) {
        MasterOut_V_strb_V_1_payload_A = tmp_strb_V_reg_98.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_strb_V_1_load_B.read())) {
        MasterOut_V_strb_V_1_payload_B = tmp_strb_V_reg_98.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && !(esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_data_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_strb_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_last_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())))))) {
        ap_reg_pp0_iter1_tmp_reg_89 = tmp_reg_89.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter0_fsm_state1.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_nbreadreq_fu_42_p5.read()) && !((esl_seteq<1,1,1>(ap_const_lv1_1, tmp_nbreadreq_fu_42_p5.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, slaveIn_TVALID.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_data_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_strb_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_last_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())))))) {
        tmp_data_V_reg_93 = slaveIn_TDATA.read();
        tmp_last_V_reg_103 = slaveIn_TLAST.read();
        tmp_strb_V_reg_98 = slaveIn_TSTRB.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter0_fsm_state1.read()) && !((esl_seteq<1,1,1>(ap_const_lv1_1, tmp_nbreadreq_fu_42_p5.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, slaveIn_TVALID.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_data_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_strb_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_last_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())))))) {
        tmp_reg_89 = tmp_nbreadreq_fu_42_p5.read();
    }
}

void my_ip_hls::thread_MasterOut_TDATA() {
    MasterOut_TDATA = MasterOut_V_data_V_1_data_out.read();
}

void my_ip_hls::thread_MasterOut_TDATA_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_reg_89.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, ap_reg_pp0_iter1_tmp_reg_89.read())))) {
        MasterOut_TDATA_blk_n = MasterOut_V_data_V_1_state.read()[1];
    } else {
        MasterOut_TDATA_blk_n = ap_const_logic_1;
    }
}

void my_ip_hls::thread_MasterOut_TLAST() {
    MasterOut_TLAST = MasterOut_V_last_V_1_data_out.read();
}

void my_ip_hls::thread_MasterOut_TSTRB() {
    MasterOut_TSTRB = MasterOut_V_strb_V_1_data_out.read();
}

void my_ip_hls::thread_MasterOut_TVALID() {
    MasterOut_TVALID = MasterOut_V_last_V_1_state.read()[0];
}

void my_ip_hls::thread_MasterOut_V_data_V_1_ack_in() {
    MasterOut_V_data_V_1_ack_in = MasterOut_V_data_V_1_state.read()[1];
}

void my_ip_hls::thread_MasterOut_V_data_V_1_ack_out() {
    MasterOut_V_data_V_1_ack_out = MasterOut_TREADY.read();
}

void my_ip_hls::thread_MasterOut_V_data_V_1_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_data_V_1_sel.read())) {
        MasterOut_V_data_V_1_data_out = MasterOut_V_data_V_1_payload_B.read();
    } else {
        MasterOut_V_data_V_1_data_out = MasterOut_V_data_V_1_payload_A.read();
    }
}

void my_ip_hls::thread_MasterOut_V_data_V_1_load_A() {
    MasterOut_V_data_V_1_load_A = (MasterOut_V_data_V_1_state_cmp_full.read() & ~MasterOut_V_data_V_1_sel_wr.read());
}

void my_ip_hls::thread_MasterOut_V_data_V_1_load_B() {
    MasterOut_V_data_V_1_load_B = (MasterOut_V_data_V_1_sel_wr.read() & MasterOut_V_data_V_1_state_cmp_full.read());
}

void my_ip_hls::thread_MasterOut_V_data_V_1_sel() {
    MasterOut_V_data_V_1_sel = MasterOut_V_data_V_1_sel_rd.read();
}

void my_ip_hls::thread_MasterOut_V_data_V_1_state_cmp_full() {
    MasterOut_V_data_V_1_state_cmp_full =  (sc_logic) ((!MasterOut_V_data_V_1_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(MasterOut_V_data_V_1_state.read() != ap_const_lv2_1))[0];
}

void my_ip_hls::thread_MasterOut_V_data_V_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_reg_89.read()) && 
         !(esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_data_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_strb_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_last_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())))))) {
        MasterOut_V_data_V_1_vld_in = ap_const_logic_1;
    } else {
        MasterOut_V_data_V_1_vld_in = ap_const_logic_0;
    }
}

void my_ip_hls::thread_MasterOut_V_data_V_1_vld_out() {
    MasterOut_V_data_V_1_vld_out = MasterOut_V_data_V_1_state.read()[0];
}

void my_ip_hls::thread_MasterOut_V_last_V_1_ack_in() {
    MasterOut_V_last_V_1_ack_in = MasterOut_V_last_V_1_state.read()[1];
}

void my_ip_hls::thread_MasterOut_V_last_V_1_ack_out() {
    MasterOut_V_last_V_1_ack_out = MasterOut_TREADY.read();
}

void my_ip_hls::thread_MasterOut_V_last_V_1_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_last_V_1_sel.read())) {
        MasterOut_V_last_V_1_data_out = MasterOut_V_last_V_1_payload_B.read();
    } else {
        MasterOut_V_last_V_1_data_out = MasterOut_V_last_V_1_payload_A.read();
    }
}

void my_ip_hls::thread_MasterOut_V_last_V_1_load_A() {
    MasterOut_V_last_V_1_load_A = (MasterOut_V_last_V_1_state_cmp_full.read() & ~MasterOut_V_last_V_1_sel_wr.read());
}

void my_ip_hls::thread_MasterOut_V_last_V_1_load_B() {
    MasterOut_V_last_V_1_load_B = (MasterOut_V_last_V_1_sel_wr.read() & MasterOut_V_last_V_1_state_cmp_full.read());
}

void my_ip_hls::thread_MasterOut_V_last_V_1_sel() {
    MasterOut_V_last_V_1_sel = MasterOut_V_last_V_1_sel_rd.read();
}

void my_ip_hls::thread_MasterOut_V_last_V_1_state_cmp_full() {
    MasterOut_V_last_V_1_state_cmp_full =  (sc_logic) ((!MasterOut_V_last_V_1_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(MasterOut_V_last_V_1_state.read() != ap_const_lv2_1))[0];
}

void my_ip_hls::thread_MasterOut_V_last_V_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_reg_89.read()) && 
         !(esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_data_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_strb_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_last_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())))))) {
        MasterOut_V_last_V_1_vld_in = ap_const_logic_1;
    } else {
        MasterOut_V_last_V_1_vld_in = ap_const_logic_0;
    }
}

void my_ip_hls::thread_MasterOut_V_last_V_1_vld_out() {
    MasterOut_V_last_V_1_vld_out = MasterOut_V_last_V_1_state.read()[0];
}

void my_ip_hls::thread_MasterOut_V_strb_V_1_ack_in() {
    MasterOut_V_strb_V_1_ack_in = MasterOut_V_strb_V_1_state.read()[1];
}

void my_ip_hls::thread_MasterOut_V_strb_V_1_ack_out() {
    MasterOut_V_strb_V_1_ack_out = MasterOut_TREADY.read();
}

void my_ip_hls::thread_MasterOut_V_strb_V_1_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, MasterOut_V_strb_V_1_sel.read())) {
        MasterOut_V_strb_V_1_data_out = MasterOut_V_strb_V_1_payload_B.read();
    } else {
        MasterOut_V_strb_V_1_data_out = MasterOut_V_strb_V_1_payload_A.read();
    }
}

void my_ip_hls::thread_MasterOut_V_strb_V_1_load_A() {
    MasterOut_V_strb_V_1_load_A = (MasterOut_V_strb_V_1_state_cmp_full.read() & ~MasterOut_V_strb_V_1_sel_wr.read());
}

void my_ip_hls::thread_MasterOut_V_strb_V_1_load_B() {
    MasterOut_V_strb_V_1_load_B = (MasterOut_V_strb_V_1_sel_wr.read() & MasterOut_V_strb_V_1_state_cmp_full.read());
}

void my_ip_hls::thread_MasterOut_V_strb_V_1_sel() {
    MasterOut_V_strb_V_1_sel = MasterOut_V_strb_V_1_sel_rd.read();
}

void my_ip_hls::thread_MasterOut_V_strb_V_1_state_cmp_full() {
    MasterOut_V_strb_V_1_state_cmp_full =  (sc_logic) ((!MasterOut_V_strb_V_1_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(MasterOut_V_strb_V_1_state.read() != ap_const_lv2_1))[0];
}

void my_ip_hls::thread_MasterOut_V_strb_V_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_reg_89.read()) && 
         !(esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_data_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_strb_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_last_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())))))) {
        MasterOut_V_strb_V_1_vld_in = ap_const_logic_1;
    } else {
        MasterOut_V_strb_V_1_vld_in = ap_const_logic_0;
    }
}

void my_ip_hls::thread_MasterOut_V_strb_V_1_vld_out() {
    MasterOut_V_strb_V_1_vld_out = MasterOut_V_strb_V_1_state.read()[0];
}

void my_ip_hls::thread_ap_CS_iter0_fsm_state1() {
    ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm.read()[0];
}

void my_ip_hls::thread_ap_CS_iter1_fsm_state2() {
    ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm.read()[1];
}

void my_ip_hls::thread_ap_CS_iter2_fsm_state3() {
    ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm.read()[1];
}

void my_ip_hls::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = (esl_seteq<1,1,1>(ap_const_lv1_1, tmp_nbreadreq_fu_42_p5.read()) && esl_seteq<1,1,1>(ap_const_logic_0, slaveIn_TVALID.read()));
}

void my_ip_hls::thread_ap_block_state2_io() {
    ap_block_state2_io = (esl_seteq<1,1,1>(ap_const_lv1_1, tmp_reg_89.read()) && esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_data_V_1_ack_in.read()));
}

void my_ip_hls::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void my_ip_hls::thread_ap_block_state3_io() {
    ap_block_state3_io = (esl_seteq<1,1,1>(ap_const_lv1_1, ap_reg_pp0_iter1_tmp_reg_89.read()) && esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_data_V_1_ack_in.read()));
}

void my_ip_hls::thread_ap_block_state3_pp0_stage0_iter2() {
    ap_block_state3_pp0_stage0_iter2 = (esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_strb_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_last_V_1_ack_in.read()));
}

void my_ip_hls::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void my_ip_hls::thread_slaveIn_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter0_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_nbreadreq_fu_42_p5.read()))) {
        slaveIn_TDATA_blk_n = slaveIn_TVALID.read();
    } else {
        slaveIn_TDATA_blk_n = ap_const_logic_1;
    }
}

void my_ip_hls::thread_slaveIn_TREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter0_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_nbreadreq_fu_42_p5.read()) && 
         !((esl_seteq<1,1,1>(ap_const_lv1_1, tmp_nbreadreq_fu_42_p5.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, slaveIn_TVALID.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_data_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_strb_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_last_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())))))) {
        slaveIn_TREADY = ap_const_logic_1;
    } else {
        slaveIn_TREADY = ap_const_logic_0;
    }
}

void my_ip_hls::thread_tmp_nbreadreq_fu_42_p5() {
    tmp_nbreadreq_fu_42_p5 =  (sc_lv<1>) ((slaveIn_TVALID.read()));
}

void my_ip_hls::thread_ap_NS_iter0_fsm() {
    switch (ap_CS_iter0_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
break;
        default : 
            ap_NS_iter0_fsm = "X";
            break;
    }
}

void my_ip_hls::thread_ap_NS_iter1_fsm() {
    switch (ap_CS_iter1_fsm.read().to_uint64()) {
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter0_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_data_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_strb_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_last_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())))) && !(esl_seteq<1,1,1>(ap_const_lv1_1, tmp_nbreadreq_fu_42_p5.read()) && esl_seteq<1,1,1>(ap_const_logic_0, slaveIn_TVALID.read())))) {
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            } else if ((!(esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_data_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_strb_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_last_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())))) && (esl_seteq<1,1,1>(ap_CS_iter0_fsm_state1.read(), ap_const_logic_0) || 
  (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter0_fsm_state1.read()) && 
   esl_seteq<1,1,1>(ap_const_lv1_1, tmp_nbreadreq_fu_42_p5.read()) && 
   esl_seteq<1,1,1>(ap_const_logic_0, slaveIn_TVALID.read()))))) {
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            } else {
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            }
            break;
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter0_fsm_state1.read()) && !((esl_seteq<1,1,1>(ap_const_lv1_1, tmp_nbreadreq_fu_42_p5.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, slaveIn_TVALID.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_data_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_strb_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_last_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())))))) {
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            } else {
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            }
            break;
        default : 
            ap_NS_iter1_fsm =  (sc_lv<2>) ("XX");
            break;
    }
}

void my_ip_hls::thread_ap_NS_iter2_fsm() {
    switch (ap_CS_iter2_fsm.read().to_uint64()) {
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_strb_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_last_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())) && esl_seteq<1,1,1>(ap_block_state2_io.read(), ap_const_boolean_0))) {
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            } else if ((!(esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_strb_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_last_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())) && ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read())) || 
  esl_seteq<1,1,1>(ap_CS_iter1_fsm_state2.read(), ap_const_logic_0)))) {
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            } else {
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            }
            break;
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && !(esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_data_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_strb_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, MasterOut_V_last_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())))))) {
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            } else {
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            }
            break;
        default : 
            ap_NS_iter2_fsm =  (sc_lv<2>) ("XX");
            break;
    }
}

void my_ip_hls::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"slaveIn_TDATA\" :  \"" << slaveIn_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"slaveIn_TVALID\" :  \"" << slaveIn_TVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"slaveIn_TREADY\" :  \"" << slaveIn_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"slaveIn_TSTRB\" :  \"" << slaveIn_TSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"slaveIn_TLAST\" :  \"" << slaveIn_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"MasterOut_TDATA\" :  \"" << MasterOut_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"MasterOut_TVALID\" :  \"" << MasterOut_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"MasterOut_TREADY\" :  \"" << MasterOut_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"MasterOut_TSTRB\" :  \"" << MasterOut_TSTRB.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"MasterOut_TLAST\" :  \"" << MasterOut_TLAST.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

