// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module core (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        p_read,
        p_read1,
        p_read2,
        ps2ipFifo_V_data_V_dout,
        ps2ipFifo_V_data_V_empty_n,
        ps2ipFifo_V_data_V_read,
        ps2ipFifo_V_strb_V_dout,
        ps2ipFifo_V_strb_V_empty_n,
        ps2ipFifo_V_strb_V_read,
        ps2ipFifo_V_last_V_dout,
        ps2ipFifo_V_last_V_empty_n,
        ps2ipFifo_V_last_V_read,
        ip2psFifo_V_data_V_din,
        ip2psFifo_V_data_V_full_n,
        ip2psFifo_V_data_V_write,
        ip2psFifo_V_strb_V_din,
        ip2psFifo_V_strb_V_full_n,
        ip2psFifo_V_strb_V_write,
        ip2psFifo_V_last_V_din,
        ip2psFifo_V_last_V_full_n,
        ip2psFifo_V_last_V_write,
        ap_return_0,
        ap_return_1,
        ap_return_2
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] p_read;
input  [31:0] p_read1;
input  [31:0] p_read2;
input  [31:0] ps2ipFifo_V_data_V_dout;
input   ps2ipFifo_V_data_V_empty_n;
output   ps2ipFifo_V_data_V_read;
input  [3:0] ps2ipFifo_V_strb_V_dout;
input   ps2ipFifo_V_strb_V_empty_n;
output   ps2ipFifo_V_strb_V_read;
input  [0:0] ps2ipFifo_V_last_V_dout;
input   ps2ipFifo_V_last_V_empty_n;
output   ps2ipFifo_V_last_V_read;
output  [31:0] ip2psFifo_V_data_V_din;
input   ip2psFifo_V_data_V_full_n;
output   ip2psFifo_V_data_V_write;
output  [3:0] ip2psFifo_V_strb_V_din;
input   ip2psFifo_V_strb_V_full_n;
output   ip2psFifo_V_strb_V_write;
output  [0:0] ip2psFifo_V_last_V_din;
input   ip2psFifo_V_last_V_full_n;
output   ip2psFifo_V_last_V_write;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;
output  [31:0] ap_return_2;

reg ap_done;
reg ap_idle;
reg start_write;
reg[31:0] ap_return_0;
reg[31:0] ap_return_1;
reg[31:0] ap_return_2;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg    internal_ap_ready;
wire    ps2ipFifo_V_data_V0_status;
wire   [0:0] tmp_nbreadreq_fu_74_p5;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ip2psFifo_V_data_V1_status;
reg   [0:0] tmp_reg_256;
reg   [0:0] tmp_6_i_i_reg_275;
reg   [0:0] tmp_8_i_i_reg_300;
reg   [0:0] tmp_i_i_reg_304;
reg    ap_predicate_op39_write_state2;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state2;
reg   [31:0] cnt0Reg_core_V;
reg   [31:0] cnt1Reg_core_V;
reg   [31:0] cnt2Reg_core_V;
reg    ps2ipFifo_V_data_V_blk_n;
reg    ps2ipFifo_V_strb_V_blk_n;
reg    ps2ipFifo_V_last_V_blk_n;
reg    ip2psFifo_V_data_V_blk_n;
reg    ip2psFifo_V_strb_V_blk_n;
reg    ip2psFifo_V_last_V_blk_n;
reg   [31:0] tmp_data_V_reg_260;
reg   [3:0] tmp_strb_V_reg_265;
reg   [0:0] tmp_last_V_reg_270;
wire   [0:0] tmp_6_i_i_fu_172_p2;
wire   [0:0] tmp_8_i_i_fu_190_p2;
wire   [0:0] tmp_i_i_fu_196_p2;
wire   [31:0] tmp_1_i_i_fu_202_p2;
wire   [31:0] tmp_9_i_i_fu_214_p2;
wire   [31:0] tmp_7_i_i_fu_226_p2;
wire   [31:0] ap_phi_reg_pp0_iter0_cnt1Reg_V_write_assi_reg_109;
reg   [31:0] ap_phi_reg_pp0_iter1_cnt1Reg_V_write_assi_reg_109;
wire   [31:0] ap_phi_reg_pp0_iter0_cnt2Reg_V_write_assi_reg_126;
reg   [31:0] ap_phi_reg_pp0_iter1_cnt2Reg_V_write_assi_reg_126;
wire   [31:0] ap_phi_reg_pp0_iter0_cnt0Reg_V_write_assi_reg_143;
reg   [31:0] ap_phi_reg_pp0_iter1_cnt0Reg_V_write_assi_reg_143;
reg    ps2ipFifo_V_data_V0_update;
reg    ip2psFifo_V_data_V1_update;
reg   [31:0] ap_return_0_preg;
reg   [31:0] ap_return_1_preg;
reg   [31:0] ap_return_2_preg;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 cnt0Reg_core_V = 32'd0;
#0 cnt1Reg_core_V = 32'd0;
#0 cnt2Reg_core_V = 32'd0;
#0 ap_return_0_preg = 32'd0;
#0 ap_return_1_preg = 32'd0;
#0 ap_return_2_preg = 32'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (ap_predicate_op39_write_state2 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 32'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (ap_predicate_op39_write_state2 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
            ap_return_0_preg <= ap_phi_reg_pp0_iter1_cnt0Reg_V_write_assi_reg_143;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 32'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (ap_predicate_op39_write_state2 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
            ap_return_1_preg <= ap_phi_reg_pp0_iter1_cnt1Reg_V_write_assi_reg_109;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 32'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (ap_predicate_op39_write_state2 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
            ap_return_2_preg <= ap_phi_reg_pp0_iter1_cnt2Reg_V_write_assi_reg_126;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((~((real_start == 1'b0) | (ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op39_write_state2 == 1'b1)) | ((tmp_nbreadreq_fu_74_p5 == 1'd1) & (ps2ipFifo_V_data_V0_status == 1'b0))) & (tmp_6_i_i_fu_172_p2 == 1'd0) & (tmp_8_i_i_fu_190_p2 == 1'd1) & (tmp_nbreadreq_fu_74_p5 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op39_write_state2 == 1'b1)) | ((tmp_nbreadreq_fu_74_p5 == 1'd1) & (ps2ipFifo_V_data_V0_status == 1'b0))) & (tmp_i_i_fu_196_p2 == 1'd0) & (tmp_8_i_i_fu_190_p2 == 1'd0) & (tmp_6_i_i_fu_172_p2 == 1'd0) & (tmp_nbreadreq_fu_74_p5 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op39_write_state2 == 1'b1)) | ((tmp_nbreadreq_fu_74_p5 == 1'd1) & (ps2ipFifo_V_data_V0_status == 1'b0))) & (tmp_8_i_i_fu_190_p2 == 1'd0) & (tmp_6_i_i_fu_172_p2 == 1'd0) & (tmp_i_i_fu_196_p2 == 1'd1) & (tmp_nbreadreq_fu_74_p5 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        ap_phi_reg_pp0_iter1_cnt0Reg_V_write_assi_reg_143 <= cnt0Reg_core_V;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op39_write_state2 == 1'b1)) | ((tmp_nbreadreq_fu_74_p5 == 1'd1) & (ps2ipFifo_V_data_V0_status == 1'b0))) & (tmp_6_i_i_fu_172_p2 == 1'd1) & (tmp_nbreadreq_fu_74_p5 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_phi_reg_pp0_iter1_cnt0Reg_V_write_assi_reg_143 <= tmp_7_i_i_fu_226_p2;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op39_write_state2 == 1'b1)) | ((tmp_nbreadreq_fu_74_p5 == 1'd1) & (ps2ipFifo_V_data_V0_status == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_phi_reg_pp0_iter1_cnt0Reg_V_write_assi_reg_143 <= ap_phi_reg_pp0_iter0_cnt0Reg_V_write_assi_reg_143;
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op39_write_state2 == 1'b1)) | ((tmp_nbreadreq_fu_74_p5 == 1'd1) & (ps2ipFifo_V_data_V0_status == 1'b0))) & (tmp_6_i_i_fu_172_p2 == 1'd0) & (tmp_8_i_i_fu_190_p2 == 1'd1) & (tmp_nbreadreq_fu_74_p5 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_phi_reg_pp0_iter1_cnt1Reg_V_write_assi_reg_109 <= tmp_9_i_i_fu_214_p2;
    end else if (((~((real_start == 1'b0) | (ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op39_write_state2 == 1'b1)) | ((tmp_nbreadreq_fu_74_p5 == 1'd1) & (ps2ipFifo_V_data_V0_status == 1'b0))) & (tmp_6_i_i_fu_172_p2 == 1'd1) & (tmp_nbreadreq_fu_74_p5 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op39_write_state2 == 1'b1)) | ((tmp_nbreadreq_fu_74_p5 == 1'd1) & (ps2ipFifo_V_data_V0_status == 1'b0))) & (tmp_i_i_fu_196_p2 == 1'd0) & (tmp_8_i_i_fu_190_p2 == 1'd0) & (tmp_6_i_i_fu_172_p2 == 1'd0) & (tmp_nbreadreq_fu_74_p5 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op39_write_state2 == 1'b1)) | ((tmp_nbreadreq_fu_74_p5 == 1'd1) & (ps2ipFifo_V_data_V0_status == 1'b0))) & (tmp_8_i_i_fu_190_p2 == 1'd0) & (tmp_6_i_i_fu_172_p2 == 1'd0) & (tmp_i_i_fu_196_p2 == 1'd1) & (tmp_nbreadreq_fu_74_p5 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        ap_phi_reg_pp0_iter1_cnt1Reg_V_write_assi_reg_109 <= cnt1Reg_core_V;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op39_write_state2 == 1'b1)) | ((tmp_nbreadreq_fu_74_p5 == 1'd1) & (ps2ipFifo_V_data_V0_status == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_phi_reg_pp0_iter1_cnt1Reg_V_write_assi_reg_109 <= ap_phi_reg_pp0_iter0_cnt1Reg_V_write_assi_reg_109;
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op39_write_state2 == 1'b1)) | ((tmp_nbreadreq_fu_74_p5 == 1'd1) & (ps2ipFifo_V_data_V0_status == 1'b0))) & (tmp_8_i_i_fu_190_p2 == 1'd0) & (tmp_6_i_i_fu_172_p2 == 1'd0) & (tmp_i_i_fu_196_p2 == 1'd1) & (tmp_nbreadreq_fu_74_p5 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_phi_reg_pp0_iter1_cnt2Reg_V_write_assi_reg_126 <= tmp_1_i_i_fu_202_p2;
    end else if (((~((real_start == 1'b0) | (ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op39_write_state2 == 1'b1)) | ((tmp_nbreadreq_fu_74_p5 == 1'd1) & (ps2ipFifo_V_data_V0_status == 1'b0))) & (tmp_6_i_i_fu_172_p2 == 1'd1) & (tmp_nbreadreq_fu_74_p5 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op39_write_state2 == 1'b1)) | ((tmp_nbreadreq_fu_74_p5 == 1'd1) & (ps2ipFifo_V_data_V0_status == 1'b0))) & (tmp_6_i_i_fu_172_p2 == 1'd0) & (tmp_8_i_i_fu_190_p2 == 1'd1) & (tmp_nbreadreq_fu_74_p5 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op39_write_state2 == 1'b1)) | ((tmp_nbreadreq_fu_74_p5 == 1'd1) & (ps2ipFifo_V_data_V0_status == 1'b0))) & (tmp_i_i_fu_196_p2 == 1'd0) & (tmp_8_i_i_fu_190_p2 == 1'd0) & (tmp_6_i_i_fu_172_p2 == 1'd0) & (tmp_nbreadreq_fu_74_p5 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        ap_phi_reg_pp0_iter1_cnt2Reg_V_write_assi_reg_126 <= cnt2Reg_core_V;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op39_write_state2 == 1'b1)) | ((tmp_nbreadreq_fu_74_p5 == 1'd1) & (ps2ipFifo_V_data_V0_status == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_phi_reg_pp0_iter1_cnt2Reg_V_write_assi_reg_126 <= ap_phi_reg_pp0_iter0_cnt2Reg_V_write_assi_reg_126;
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op39_write_state2 == 1'b1)) | ((tmp_nbreadreq_fu_74_p5 == 1'd1) & (ps2ipFifo_V_data_V0_status == 1'b0))) & (tmp_6_i_i_fu_172_p2 == 1'd1) & (tmp_nbreadreq_fu_74_p5 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        cnt0Reg_core_V <= tmp_7_i_i_fu_226_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op39_write_state2 == 1'b1)) | ((tmp_nbreadreq_fu_74_p5 == 1'd1) & (ps2ipFifo_V_data_V0_status == 1'b0))) & (tmp_6_i_i_fu_172_p2 == 1'd0) & (tmp_8_i_i_fu_190_p2 == 1'd1) & (tmp_nbreadreq_fu_74_p5 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        cnt1Reg_core_V <= tmp_9_i_i_fu_214_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op39_write_state2 == 1'b1)) | ((tmp_nbreadreq_fu_74_p5 == 1'd1) & (ps2ipFifo_V_data_V0_status == 1'b0))) & (tmp_8_i_i_fu_190_p2 == 1'd0) & (tmp_6_i_i_fu_172_p2 == 1'd0) & (tmp_i_i_fu_196_p2 == 1'd1) & (tmp_nbreadreq_fu_74_p5 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        cnt2Reg_core_V <= tmp_1_i_i_fu_202_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op39_write_state2 == 1'b1)) | ((tmp_nbreadreq_fu_74_p5 == 1'd1) & (ps2ipFifo_V_data_V0_status == 1'b0))) & (tmp_nbreadreq_fu_74_p5 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        tmp_6_i_i_reg_275 <= tmp_6_i_i_fu_172_p2;
        tmp_data_V_reg_260 <= ps2ipFifo_V_data_V_dout;
        tmp_last_V_reg_270 <= ps2ipFifo_V_last_V_dout;
        tmp_strb_V_reg_265 <= ps2ipFifo_V_strb_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op39_write_state2 == 1'b1)) | ((tmp_nbreadreq_fu_74_p5 == 1'd1) & (ps2ipFifo_V_data_V0_status == 1'b0))) & (tmp_6_i_i_fu_172_p2 == 1'd0) & (tmp_nbreadreq_fu_74_p5 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        tmp_8_i_i_reg_300 <= tmp_8_i_i_fu_190_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op39_write_state2 == 1'b1)) | ((tmp_nbreadreq_fu_74_p5 == 1'd1) & (ps2ipFifo_V_data_V0_status == 1'b0))) & (tmp_8_i_i_fu_190_p2 == 1'd0) & (tmp_6_i_i_fu_172_p2 == 1'd0) & (tmp_nbreadreq_fu_74_p5 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        tmp_i_i_reg_304 <= tmp_i_i_fu_196_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op39_write_state2 == 1'b1)) | ((tmp_nbreadreq_fu_74_p5 == 1'd1) & (ps2ipFifo_V_data_V0_status == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        tmp_reg_256 <= tmp_nbreadreq_fu_74_p5;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (ap_predicate_op39_write_state2 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (ap_predicate_op39_write_state2 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_return_0 = ap_phi_reg_pp0_iter1_cnt0Reg_V_write_assi_reg_143;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (ap_predicate_op39_write_state2 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_return_1 = ap_phi_reg_pp0_iter1_cnt1Reg_V_write_assi_reg_109;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (ap_predicate_op39_write_state2 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_return_2 = ap_phi_reg_pp0_iter1_cnt2Reg_V_write_assi_reg_126;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op39_write_state2 == 1'b1)) | ((tmp_nbreadreq_fu_74_p5 == 1'd1) & (ps2ipFifo_V_data_V0_status == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (ap_predicate_op39_write_state2 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op39_write_state2 == 1'b1))) begin
        ip2psFifo_V_data_V1_update = 1'b1;
    end else begin
        ip2psFifo_V_data_V1_update = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op39_write_state2 == 1'b1))) begin
        ip2psFifo_V_data_V_blk_n = ip2psFifo_V_data_V_full_n;
    end else begin
        ip2psFifo_V_data_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op39_write_state2 == 1'b1))) begin
        ip2psFifo_V_last_V_blk_n = ip2psFifo_V_last_V_full_n;
    end else begin
        ip2psFifo_V_last_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op39_write_state2 == 1'b1))) begin
        ip2psFifo_V_strb_V_blk_n = ip2psFifo_V_strb_V_full_n;
    end else begin
        ip2psFifo_V_strb_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op39_write_state2 == 1'b1)) | ((tmp_nbreadreq_fu_74_p5 == 1'd1) & (ps2ipFifo_V_data_V0_status == 1'b0))) & (tmp_nbreadreq_fu_74_p5 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ps2ipFifo_V_data_V0_update = 1'b1;
    end else begin
        ps2ipFifo_V_data_V0_update = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (tmp_nbreadreq_fu_74_p5 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (real_start == 1'b1))) begin
        ps2ipFifo_V_data_V_blk_n = ps2ipFifo_V_data_V_empty_n;
    end else begin
        ps2ipFifo_V_data_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (tmp_nbreadreq_fu_74_p5 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (real_start == 1'b1))) begin
        ps2ipFifo_V_last_V_blk_n = ps2ipFifo_V_last_V_empty_n;
    end else begin
        ps2ipFifo_V_last_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (tmp_nbreadreq_fu_74_p5 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (real_start == 1'b1))) begin
        ps2ipFifo_V_strb_V_blk_n = ps2ipFifo_V_strb_V_empty_n;
    end else begin
        ps2ipFifo_V_strb_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_nbreadreq_fu_74_p5 == 1'd1) & (ps2ipFifo_V_data_V0_status == 1'b0))) & ~((ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (ap_predicate_op39_write_state2 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (ap_predicate_op39_write_state2 == 1'b1))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & ((real_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_nbreadreq_fu_74_p5 == 1'd1) & (ps2ipFifo_V_data_V0_status == 1'b0))))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1) | ((ip2psFifo_V_data_V1_status == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op39_write_state2 == 1'b1)) | ((tmp_nbreadreq_fu_74_p5 == 1'd1) & (ps2ipFifo_V_data_V0_status == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((real_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_nbreadreq_fu_74_p5 == 1'd1) & (ps2ipFifo_V_data_V0_status == 1'b0)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((ip2psFifo_V_data_V1_status == 1'b0) & (ap_predicate_op39_write_state2 == 1'b1));
end

assign ap_phi_reg_pp0_iter0_cnt0Reg_V_write_assi_reg_143 = 'bx;

assign ap_phi_reg_pp0_iter0_cnt1Reg_V_write_assi_reg_109 = 'bx;

assign ap_phi_reg_pp0_iter0_cnt2Reg_V_write_assi_reg_126 = 'bx;

always @ (*) begin
    ap_predicate_op39_write_state2 = ((tmp_i_i_reg_304 == 1'd0) & (tmp_8_i_i_reg_300 == 1'd0) & (tmp_6_i_i_reg_275 == 1'd0) & (tmp_reg_256 == 1'd1));
end

assign ap_ready = internal_ap_ready;

assign ip2psFifo_V_data_V1_status = (ip2psFifo_V_strb_V_full_n & ip2psFifo_V_last_V_full_n & ip2psFifo_V_data_V_full_n);

assign ip2psFifo_V_data_V_din = tmp_data_V_reg_260;

assign ip2psFifo_V_data_V_write = ip2psFifo_V_data_V1_update;

assign ip2psFifo_V_last_V_din = tmp_last_V_reg_270;

assign ip2psFifo_V_last_V_write = ip2psFifo_V_data_V1_update;

assign ip2psFifo_V_strb_V_din = tmp_strb_V_reg_265;

assign ip2psFifo_V_strb_V_write = ip2psFifo_V_data_V1_update;

assign ps2ipFifo_V_data_V0_status = (ps2ipFifo_V_strb_V_empty_n & ps2ipFifo_V_last_V_empty_n & ps2ipFifo_V_data_V_empty_n);

assign ps2ipFifo_V_data_V_read = ps2ipFifo_V_data_V0_update;

assign ps2ipFifo_V_last_V_read = ps2ipFifo_V_data_V0_update;

assign ps2ipFifo_V_strb_V_read = ps2ipFifo_V_data_V0_update;

assign start_out = real_start;

assign tmp_1_i_i_fu_202_p2 = (cnt2Reg_core_V + 32'd1);

assign tmp_6_i_i_fu_172_p2 = ((ps2ipFifo_V_data_V_dout == p_read) ? 1'b1 : 1'b0);

assign tmp_7_i_i_fu_226_p2 = (cnt0Reg_core_V + 32'd1);

assign tmp_8_i_i_fu_190_p2 = ((ps2ipFifo_V_data_V_dout == p_read1) ? 1'b1 : 1'b0);

assign tmp_9_i_i_fu_214_p2 = (cnt1Reg_core_V + 32'd1);

assign tmp_i_i_fu_196_p2 = ((ps2ipFifo_V_data_V_dout == p_read2) ? 1'b1 : 1'b0);

assign tmp_nbreadreq_fu_74_p5 = (ps2ipFifo_V_strb_V_empty_n & ps2ipFifo_V_last_V_empty_n & ps2ipFifo_V_data_V_empty_n);

endmodule //core
