// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "my_ip_hls.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_lv<32> my_ip_hls::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<4> my_ip_hls::ap_const_lv4_0 = "0000";
const sc_lv<1> my_ip_hls::ap_const_lv1_0 = "0";
const sc_logic my_ip_hls::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic my_ip_hls::ap_const_logic_0 = sc_dt::Log_0;

my_ip_hls::my_ip_hls(sc_module_name name) : sc_module(name), mVcdFile(0) {
    ps2ip_fifo_U0 = new ps2ip_fifo("ps2ip_fifo_U0");
    ps2ip_fifo_U0->ap_clk(ap_clk);
    ps2ip_fifo_U0->ap_rst(ap_rst_n_inv);
    ps2ip_fifo_U0->ap_start(ps2ip_fifo_U0_ap_start);
    ps2ip_fifo_U0->start_full_n(start_for_core_U0_full_n);
    ps2ip_fifo_U0->ap_done(ps2ip_fifo_U0_ap_done);
    ps2ip_fifo_U0->ap_continue(ps2ip_fifo_U0_ap_continue);
    ps2ip_fifo_U0->ap_idle(ps2ip_fifo_U0_ap_idle);
    ps2ip_fifo_U0->ap_ready(ps2ip_fifo_U0_ap_ready);
    ps2ip_fifo_U0->slaveIn_TVALID(slaveIn_TVALID);
    ps2ip_fifo_U0->start_out(ps2ip_fifo_U0_start_out);
    ps2ip_fifo_U0->start_write(ps2ip_fifo_U0_start_write);
    ps2ip_fifo_U0->slaveIn_TDATA(slaveIn_TDATA);
    ps2ip_fifo_U0->slaveIn_TREADY(ps2ip_fifo_U0_slaveIn_TREADY);
    ps2ip_fifo_U0->slaveIn_TSTRB(slaveIn_TSTRB);
    ps2ip_fifo_U0->slaveIn_TLAST(slaveIn_TLAST);
    ps2ip_fifo_U0->ps2ipFifo_V_data_V_din(ps2ip_fifo_U0_ps2ipFifo_V_data_V_din);
    ps2ip_fifo_U0->ps2ipFifo_V_data_V_full_n(ps2ipFifo_V_data_V_full_n);
    ps2ip_fifo_U0->ps2ipFifo_V_data_V_write(ps2ip_fifo_U0_ps2ipFifo_V_data_V_write);
    ps2ip_fifo_U0->ps2ipFifo_V_strb_V_din(ps2ip_fifo_U0_ps2ipFifo_V_strb_V_din);
    ps2ip_fifo_U0->ps2ipFifo_V_strb_V_full_n(ps2ipFifo_V_strb_V_full_n);
    ps2ip_fifo_U0->ps2ipFifo_V_strb_V_write(ps2ip_fifo_U0_ps2ipFifo_V_strb_V_write);
    ps2ip_fifo_U0->ps2ipFifo_V_last_V_din(ps2ip_fifo_U0_ps2ipFifo_V_last_V_din);
    ps2ip_fifo_U0->ps2ipFifo_V_last_V_full_n(ps2ipFifo_V_last_V_full_n);
    ps2ip_fifo_U0->ps2ipFifo_V_last_V_write(ps2ip_fifo_U0_ps2ipFifo_V_last_V_write);
    core_U0 = new core("core_U0");
    core_U0->ap_clk(ap_clk);
    core_U0->ap_rst(ap_rst_n_inv);
    core_U0->ap_start(core_U0_ap_start);
    core_U0->start_full_n(start_for_ip2ps_fifo_U0_full_n);
    core_U0->ap_done(core_U0_ap_done);
    core_U0->ap_continue(core_U0_ap_continue);
    core_U0->ap_idle(core_U0_ap_idle);
    core_U0->ap_ready(core_U0_ap_ready);
    core_U0->start_out(core_U0_start_out);
    core_U0->start_write(core_U0_start_write);
    core_U0->ps2ipFifo_V_data_V_dout(ps2ipFifo_V_data_V_dout);
    core_U0->ps2ipFifo_V_data_V_empty_n(ps2ipFifo_V_data_V_empty_n);
    core_U0->ps2ipFifo_V_data_V_read(core_U0_ps2ipFifo_V_data_V_read);
    core_U0->ps2ipFifo_V_strb_V_dout(ps2ipFifo_V_strb_V_dout);
    core_U0->ps2ipFifo_V_strb_V_empty_n(ps2ipFifo_V_strb_V_empty_n);
    core_U0->ps2ipFifo_V_strb_V_read(core_U0_ps2ipFifo_V_strb_V_read);
    core_U0->ps2ipFifo_V_last_V_dout(ps2ipFifo_V_last_V_dout);
    core_U0->ps2ipFifo_V_last_V_empty_n(ps2ipFifo_V_last_V_empty_n);
    core_U0->ps2ipFifo_V_last_V_read(core_U0_ps2ipFifo_V_last_V_read);
    core_U0->ip2psFifo_V_data_V_din(core_U0_ip2psFifo_V_data_V_din);
    core_U0->ip2psFifo_V_data_V_full_n(ip2psFifo_V_data_V_full_n);
    core_U0->ip2psFifo_V_data_V_write(core_U0_ip2psFifo_V_data_V_write);
    core_U0->ip2psFifo_V_strb_V_din(core_U0_ip2psFifo_V_strb_V_din);
    core_U0->ip2psFifo_V_strb_V_full_n(ip2psFifo_V_strb_V_full_n);
    core_U0->ip2psFifo_V_strb_V_write(core_U0_ip2psFifo_V_strb_V_write);
    core_U0->ip2psFifo_V_last_V_din(core_U0_ip2psFifo_V_last_V_din);
    core_U0->ip2psFifo_V_last_V_full_n(ip2psFifo_V_last_V_full_n);
    core_U0->ip2psFifo_V_last_V_write(core_U0_ip2psFifo_V_last_V_write);
    ip2ps_fifo_U0 = new ip2ps_fifo("ip2ps_fifo_U0");
    ip2ps_fifo_U0->ap_clk(ap_clk);
    ip2ps_fifo_U0->ap_rst(ap_rst_n_inv);
    ip2ps_fifo_U0->ap_start(ip2ps_fifo_U0_ap_start);
    ip2ps_fifo_U0->ap_done(ip2ps_fifo_U0_ap_done);
    ip2ps_fifo_U0->ap_continue(ip2ps_fifo_U0_ap_continue);
    ip2ps_fifo_U0->ap_idle(ip2ps_fifo_U0_ap_idle);
    ip2ps_fifo_U0->ap_ready(ip2ps_fifo_U0_ap_ready);
    ip2ps_fifo_U0->masterOut_TREADY(masterOut_TREADY);
    ip2ps_fifo_U0->masterOut_TDATA(ip2ps_fifo_U0_masterOut_TDATA);
    ip2ps_fifo_U0->masterOut_TVALID(ip2ps_fifo_U0_masterOut_TVALID);
    ip2ps_fifo_U0->masterOut_TSTRB(ip2ps_fifo_U0_masterOut_TSTRB);
    ip2ps_fifo_U0->masterOut_TLAST(ip2ps_fifo_U0_masterOut_TLAST);
    ip2ps_fifo_U0->ip2psFifo_V_data_V_dout(ip2psFifo_V_data_V_dout);
    ip2ps_fifo_U0->ip2psFifo_V_data_V_empty_n(ip2psFifo_V_data_V_empty_n);
    ip2ps_fifo_U0->ip2psFifo_V_data_V_read(ip2ps_fifo_U0_ip2psFifo_V_data_V_read);
    ip2ps_fifo_U0->ip2psFifo_V_strb_V_dout(ip2psFifo_V_strb_V_dout);
    ip2ps_fifo_U0->ip2psFifo_V_strb_V_empty_n(ip2psFifo_V_strb_V_empty_n);
    ip2ps_fifo_U0->ip2psFifo_V_strb_V_read(ip2ps_fifo_U0_ip2psFifo_V_strb_V_read);
    ip2ps_fifo_U0->ip2psFifo_V_last_V_dout(ip2psFifo_V_last_V_dout);
    ip2ps_fifo_U0->ip2psFifo_V_last_V_empty_n(ip2psFifo_V_last_V_empty_n);
    ip2ps_fifo_U0->ip2psFifo_V_last_V_read(ip2ps_fifo_U0_ip2psFifo_V_last_V_read);
    ps2ipFifo_V_data_V_U = new fifo_w32_d64_A("ps2ipFifo_V_data_V_U");
    ps2ipFifo_V_data_V_U->clk(ap_clk);
    ps2ipFifo_V_data_V_U->reset(ap_rst_n_inv);
    ps2ipFifo_V_data_V_U->if_read_ce(ap_var_for_const0);
    ps2ipFifo_V_data_V_U->if_write_ce(ap_var_for_const0);
    ps2ipFifo_V_data_V_U->if_din(ps2ip_fifo_U0_ps2ipFifo_V_data_V_din);
    ps2ipFifo_V_data_V_U->if_full_n(ps2ipFifo_V_data_V_full_n);
    ps2ipFifo_V_data_V_U->if_write(ps2ip_fifo_U0_ps2ipFifo_V_data_V_write);
    ps2ipFifo_V_data_V_U->if_dout(ps2ipFifo_V_data_V_dout);
    ps2ipFifo_V_data_V_U->if_empty_n(ps2ipFifo_V_data_V_empty_n);
    ps2ipFifo_V_data_V_U->if_read(core_U0_ps2ipFifo_V_data_V_read);
    ps2ipFifo_V_strb_V_U = new fifo_w4_d64_A("ps2ipFifo_V_strb_V_U");
    ps2ipFifo_V_strb_V_U->clk(ap_clk);
    ps2ipFifo_V_strb_V_U->reset(ap_rst_n_inv);
    ps2ipFifo_V_strb_V_U->if_read_ce(ap_var_for_const0);
    ps2ipFifo_V_strb_V_U->if_write_ce(ap_var_for_const0);
    ps2ipFifo_V_strb_V_U->if_din(ps2ip_fifo_U0_ps2ipFifo_V_strb_V_din);
    ps2ipFifo_V_strb_V_U->if_full_n(ps2ipFifo_V_strb_V_full_n);
    ps2ipFifo_V_strb_V_U->if_write(ps2ip_fifo_U0_ps2ipFifo_V_strb_V_write);
    ps2ipFifo_V_strb_V_U->if_dout(ps2ipFifo_V_strb_V_dout);
    ps2ipFifo_V_strb_V_U->if_empty_n(ps2ipFifo_V_strb_V_empty_n);
    ps2ipFifo_V_strb_V_U->if_read(core_U0_ps2ipFifo_V_strb_V_read);
    ps2ipFifo_V_last_V_U = new fifo_w1_d64_A("ps2ipFifo_V_last_V_U");
    ps2ipFifo_V_last_V_U->clk(ap_clk);
    ps2ipFifo_V_last_V_U->reset(ap_rst_n_inv);
    ps2ipFifo_V_last_V_U->if_read_ce(ap_var_for_const0);
    ps2ipFifo_V_last_V_U->if_write_ce(ap_var_for_const0);
    ps2ipFifo_V_last_V_U->if_din(ps2ip_fifo_U0_ps2ipFifo_V_last_V_din);
    ps2ipFifo_V_last_V_U->if_full_n(ps2ipFifo_V_last_V_full_n);
    ps2ipFifo_V_last_V_U->if_write(ps2ip_fifo_U0_ps2ipFifo_V_last_V_write);
    ps2ipFifo_V_last_V_U->if_dout(ps2ipFifo_V_last_V_dout);
    ps2ipFifo_V_last_V_U->if_empty_n(ps2ipFifo_V_last_V_empty_n);
    ps2ipFifo_V_last_V_U->if_read(core_U0_ps2ipFifo_V_last_V_read);
    ip2psFifo_V_data_V_U = new fifo_w32_d64_A("ip2psFifo_V_data_V_U");
    ip2psFifo_V_data_V_U->clk(ap_clk);
    ip2psFifo_V_data_V_U->reset(ap_rst_n_inv);
    ip2psFifo_V_data_V_U->if_read_ce(ap_var_for_const0);
    ip2psFifo_V_data_V_U->if_write_ce(ap_var_for_const0);
    ip2psFifo_V_data_V_U->if_din(core_U0_ip2psFifo_V_data_V_din);
    ip2psFifo_V_data_V_U->if_full_n(ip2psFifo_V_data_V_full_n);
    ip2psFifo_V_data_V_U->if_write(core_U0_ip2psFifo_V_data_V_write);
    ip2psFifo_V_data_V_U->if_dout(ip2psFifo_V_data_V_dout);
    ip2psFifo_V_data_V_U->if_empty_n(ip2psFifo_V_data_V_empty_n);
    ip2psFifo_V_data_V_U->if_read(ip2ps_fifo_U0_ip2psFifo_V_data_V_read);
    ip2psFifo_V_strb_V_U = new fifo_w4_d64_A("ip2psFifo_V_strb_V_U");
    ip2psFifo_V_strb_V_U->clk(ap_clk);
    ip2psFifo_V_strb_V_U->reset(ap_rst_n_inv);
    ip2psFifo_V_strb_V_U->if_read_ce(ap_var_for_const0);
    ip2psFifo_V_strb_V_U->if_write_ce(ap_var_for_const0);
    ip2psFifo_V_strb_V_U->if_din(core_U0_ip2psFifo_V_strb_V_din);
    ip2psFifo_V_strb_V_U->if_full_n(ip2psFifo_V_strb_V_full_n);
    ip2psFifo_V_strb_V_U->if_write(core_U0_ip2psFifo_V_strb_V_write);
    ip2psFifo_V_strb_V_U->if_dout(ip2psFifo_V_strb_V_dout);
    ip2psFifo_V_strb_V_U->if_empty_n(ip2psFifo_V_strb_V_empty_n);
    ip2psFifo_V_strb_V_U->if_read(ip2ps_fifo_U0_ip2psFifo_V_strb_V_read);
    ip2psFifo_V_last_V_U = new fifo_w1_d64_A("ip2psFifo_V_last_V_U");
    ip2psFifo_V_last_V_U->clk(ap_clk);
    ip2psFifo_V_last_V_U->reset(ap_rst_n_inv);
    ip2psFifo_V_last_V_U->if_read_ce(ap_var_for_const0);
    ip2psFifo_V_last_V_U->if_write_ce(ap_var_for_const0);
    ip2psFifo_V_last_V_U->if_din(core_U0_ip2psFifo_V_last_V_din);
    ip2psFifo_V_last_V_U->if_full_n(ip2psFifo_V_last_V_full_n);
    ip2psFifo_V_last_V_U->if_write(core_U0_ip2psFifo_V_last_V_write);
    ip2psFifo_V_last_V_U->if_dout(ip2psFifo_V_last_V_dout);
    ip2psFifo_V_last_V_U->if_empty_n(ip2psFifo_V_last_V_empty_n);
    ip2psFifo_V_last_V_U->if_read(ip2ps_fifo_U0_ip2psFifo_V_last_V_read);
    start_for_core_U0_U = new start_for_core_U0("start_for_core_U0_U");
    start_for_core_U0_U->clk(ap_clk);
    start_for_core_U0_U->reset(ap_rst_n_inv);
    start_for_core_U0_U->if_read_ce(ap_var_for_const0);
    start_for_core_U0_U->if_write_ce(ap_var_for_const0);
    start_for_core_U0_U->if_din(start_for_core_U0_din);
    start_for_core_U0_U->if_full_n(start_for_core_U0_full_n);
    start_for_core_U0_U->if_write(ps2ip_fifo_U0_start_write);
    start_for_core_U0_U->if_dout(start_for_core_U0_dout);
    start_for_core_U0_U->if_empty_n(start_for_core_U0_empty_n);
    start_for_core_U0_U->if_read(core_U0_ap_ready);
    start_for_ip2ps_fbkb_U = new start_for_ip2ps_fbkb("start_for_ip2ps_fbkb_U");
    start_for_ip2ps_fbkb_U->clk(ap_clk);
    start_for_ip2ps_fbkb_U->reset(ap_rst_n_inv);
    start_for_ip2ps_fbkb_U->if_read_ce(ap_var_for_const0);
    start_for_ip2ps_fbkb_U->if_write_ce(ap_var_for_const0);
    start_for_ip2ps_fbkb_U->if_din(start_for_ip2ps_fifo_U0_din);
    start_for_ip2ps_fbkb_U->if_full_n(start_for_ip2ps_fifo_U0_full_n);
    start_for_ip2ps_fbkb_U->if_write(core_U0_start_write);
    start_for_ip2ps_fbkb_U->if_dout(start_for_ip2ps_fifo_U0_dout);
    start_for_ip2ps_fbkb_U->if_empty_n(start_for_ip2ps_fifo_U0_empty_n);
    start_for_ip2ps_fbkb_U->if_read(ip2ps_fifo_U0_ap_ready);

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sync_continue);

    SC_METHOD(thread_core_U0_ap_continue);

    SC_METHOD(thread_core_U0_ap_start);
    sensitive << ( start_for_core_U0_empty_n );

    SC_METHOD(thread_ip2ps_fifo_U0_ap_continue);

    SC_METHOD(thread_ip2ps_fifo_U0_ap_start);
    sensitive << ( start_for_ip2ps_fifo_U0_empty_n );

    SC_METHOD(thread_ip2ps_fifo_U0_start_full_n);

    SC_METHOD(thread_ip2ps_fifo_U0_start_write);

    SC_METHOD(thread_masterOut_TDATA);
    sensitive << ( ip2ps_fifo_U0_masterOut_TDATA );

    SC_METHOD(thread_masterOut_TLAST);
    sensitive << ( ip2ps_fifo_U0_masterOut_TLAST );

    SC_METHOD(thread_masterOut_TSTRB);
    sensitive << ( ip2ps_fifo_U0_masterOut_TSTRB );

    SC_METHOD(thread_masterOut_TVALID);
    sensitive << ( ip2ps_fifo_U0_masterOut_TVALID );

    SC_METHOD(thread_ps2ip_fifo_U0_ap_continue);

    SC_METHOD(thread_ps2ip_fifo_U0_ap_start);

    SC_METHOD(thread_slaveIn_TREADY);
    sensitive << ( ps2ip_fifo_U0_slaveIn_TREADY );

    SC_METHOD(thread_start_for_core_U0_din);

    SC_METHOD(thread_start_for_ip2ps_fifo_U0_din);

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "my_ip_hls_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, slaveIn_TDATA, "(port)slaveIn_TDATA");
    sc_trace(mVcdFile, slaveIn_TSTRB, "(port)slaveIn_TSTRB");
    sc_trace(mVcdFile, slaveIn_TLAST, "(port)slaveIn_TLAST");
    sc_trace(mVcdFile, masterOut_TDATA, "(port)masterOut_TDATA");
    sc_trace(mVcdFile, masterOut_TSTRB, "(port)masterOut_TSTRB");
    sc_trace(mVcdFile, masterOut_TLAST, "(port)masterOut_TLAST");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, slaveIn_TVALID, "(port)slaveIn_TVALID");
    sc_trace(mVcdFile, slaveIn_TREADY, "(port)slaveIn_TREADY");
    sc_trace(mVcdFile, masterOut_TVALID, "(port)masterOut_TVALID");
    sc_trace(mVcdFile, masterOut_TREADY, "(port)masterOut_TREADY");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ps2ip_fifo_U0_ap_start, "ps2ip_fifo_U0_ap_start");
    sc_trace(mVcdFile, ps2ip_fifo_U0_ap_done, "ps2ip_fifo_U0_ap_done");
    sc_trace(mVcdFile, ps2ip_fifo_U0_ap_continue, "ps2ip_fifo_U0_ap_continue");
    sc_trace(mVcdFile, ps2ip_fifo_U0_ap_idle, "ps2ip_fifo_U0_ap_idle");
    sc_trace(mVcdFile, ps2ip_fifo_U0_ap_ready, "ps2ip_fifo_U0_ap_ready");
    sc_trace(mVcdFile, ps2ip_fifo_U0_start_out, "ps2ip_fifo_U0_start_out");
    sc_trace(mVcdFile, ps2ip_fifo_U0_start_write, "ps2ip_fifo_U0_start_write");
    sc_trace(mVcdFile, ps2ip_fifo_U0_slaveIn_TREADY, "ps2ip_fifo_U0_slaveIn_TREADY");
    sc_trace(mVcdFile, ps2ip_fifo_U0_ps2ipFifo_V_data_V_din, "ps2ip_fifo_U0_ps2ipFifo_V_data_V_din");
    sc_trace(mVcdFile, ps2ip_fifo_U0_ps2ipFifo_V_data_V_write, "ps2ip_fifo_U0_ps2ipFifo_V_data_V_write");
    sc_trace(mVcdFile, ps2ip_fifo_U0_ps2ipFifo_V_strb_V_din, "ps2ip_fifo_U0_ps2ipFifo_V_strb_V_din");
    sc_trace(mVcdFile, ps2ip_fifo_U0_ps2ipFifo_V_strb_V_write, "ps2ip_fifo_U0_ps2ipFifo_V_strb_V_write");
    sc_trace(mVcdFile, ps2ip_fifo_U0_ps2ipFifo_V_last_V_din, "ps2ip_fifo_U0_ps2ipFifo_V_last_V_din");
    sc_trace(mVcdFile, ps2ip_fifo_U0_ps2ipFifo_V_last_V_write, "ps2ip_fifo_U0_ps2ipFifo_V_last_V_write");
    sc_trace(mVcdFile, core_U0_ap_start, "core_U0_ap_start");
    sc_trace(mVcdFile, core_U0_ap_done, "core_U0_ap_done");
    sc_trace(mVcdFile, core_U0_ap_continue, "core_U0_ap_continue");
    sc_trace(mVcdFile, core_U0_ap_idle, "core_U0_ap_idle");
    sc_trace(mVcdFile, core_U0_ap_ready, "core_U0_ap_ready");
    sc_trace(mVcdFile, core_U0_start_out, "core_U0_start_out");
    sc_trace(mVcdFile, core_U0_start_write, "core_U0_start_write");
    sc_trace(mVcdFile, core_U0_ps2ipFifo_V_data_V_read, "core_U0_ps2ipFifo_V_data_V_read");
    sc_trace(mVcdFile, core_U0_ps2ipFifo_V_strb_V_read, "core_U0_ps2ipFifo_V_strb_V_read");
    sc_trace(mVcdFile, core_U0_ps2ipFifo_V_last_V_read, "core_U0_ps2ipFifo_V_last_V_read");
    sc_trace(mVcdFile, core_U0_ip2psFifo_V_data_V_din, "core_U0_ip2psFifo_V_data_V_din");
    sc_trace(mVcdFile, core_U0_ip2psFifo_V_data_V_write, "core_U0_ip2psFifo_V_data_V_write");
    sc_trace(mVcdFile, core_U0_ip2psFifo_V_strb_V_din, "core_U0_ip2psFifo_V_strb_V_din");
    sc_trace(mVcdFile, core_U0_ip2psFifo_V_strb_V_write, "core_U0_ip2psFifo_V_strb_V_write");
    sc_trace(mVcdFile, core_U0_ip2psFifo_V_last_V_din, "core_U0_ip2psFifo_V_last_V_din");
    sc_trace(mVcdFile, core_U0_ip2psFifo_V_last_V_write, "core_U0_ip2psFifo_V_last_V_write");
    sc_trace(mVcdFile, ip2ps_fifo_U0_ap_start, "ip2ps_fifo_U0_ap_start");
    sc_trace(mVcdFile, ip2ps_fifo_U0_ap_done, "ip2ps_fifo_U0_ap_done");
    sc_trace(mVcdFile, ip2ps_fifo_U0_ap_continue, "ip2ps_fifo_U0_ap_continue");
    sc_trace(mVcdFile, ip2ps_fifo_U0_ap_idle, "ip2ps_fifo_U0_ap_idle");
    sc_trace(mVcdFile, ip2ps_fifo_U0_ap_ready, "ip2ps_fifo_U0_ap_ready");
    sc_trace(mVcdFile, ip2ps_fifo_U0_masterOut_TDATA, "ip2ps_fifo_U0_masterOut_TDATA");
    sc_trace(mVcdFile, ip2ps_fifo_U0_masterOut_TVALID, "ip2ps_fifo_U0_masterOut_TVALID");
    sc_trace(mVcdFile, ip2ps_fifo_U0_masterOut_TSTRB, "ip2ps_fifo_U0_masterOut_TSTRB");
    sc_trace(mVcdFile, ip2ps_fifo_U0_masterOut_TLAST, "ip2ps_fifo_U0_masterOut_TLAST");
    sc_trace(mVcdFile, ip2ps_fifo_U0_ip2psFifo_V_data_V_read, "ip2ps_fifo_U0_ip2psFifo_V_data_V_read");
    sc_trace(mVcdFile, ip2ps_fifo_U0_ip2psFifo_V_strb_V_read, "ip2ps_fifo_U0_ip2psFifo_V_strb_V_read");
    sc_trace(mVcdFile, ip2ps_fifo_U0_ip2psFifo_V_last_V_read, "ip2ps_fifo_U0_ip2psFifo_V_last_V_read");
    sc_trace(mVcdFile, ap_sync_continue, "ap_sync_continue");
    sc_trace(mVcdFile, ps2ipFifo_V_data_V_full_n, "ps2ipFifo_V_data_V_full_n");
    sc_trace(mVcdFile, ps2ipFifo_V_data_V_dout, "ps2ipFifo_V_data_V_dout");
    sc_trace(mVcdFile, ps2ipFifo_V_data_V_empty_n, "ps2ipFifo_V_data_V_empty_n");
    sc_trace(mVcdFile, ps2ipFifo_V_strb_V_full_n, "ps2ipFifo_V_strb_V_full_n");
    sc_trace(mVcdFile, ps2ipFifo_V_strb_V_dout, "ps2ipFifo_V_strb_V_dout");
    sc_trace(mVcdFile, ps2ipFifo_V_strb_V_empty_n, "ps2ipFifo_V_strb_V_empty_n");
    sc_trace(mVcdFile, ps2ipFifo_V_last_V_full_n, "ps2ipFifo_V_last_V_full_n");
    sc_trace(mVcdFile, ps2ipFifo_V_last_V_dout, "ps2ipFifo_V_last_V_dout");
    sc_trace(mVcdFile, ps2ipFifo_V_last_V_empty_n, "ps2ipFifo_V_last_V_empty_n");
    sc_trace(mVcdFile, ip2psFifo_V_data_V_full_n, "ip2psFifo_V_data_V_full_n");
    sc_trace(mVcdFile, ip2psFifo_V_data_V_dout, "ip2psFifo_V_data_V_dout");
    sc_trace(mVcdFile, ip2psFifo_V_data_V_empty_n, "ip2psFifo_V_data_V_empty_n");
    sc_trace(mVcdFile, ip2psFifo_V_strb_V_full_n, "ip2psFifo_V_strb_V_full_n");
    sc_trace(mVcdFile, ip2psFifo_V_strb_V_dout, "ip2psFifo_V_strb_V_dout");
    sc_trace(mVcdFile, ip2psFifo_V_strb_V_empty_n, "ip2psFifo_V_strb_V_empty_n");
    sc_trace(mVcdFile, ip2psFifo_V_last_V_full_n, "ip2psFifo_V_last_V_full_n");
    sc_trace(mVcdFile, ip2psFifo_V_last_V_dout, "ip2psFifo_V_last_V_dout");
    sc_trace(mVcdFile, ip2psFifo_V_last_V_empty_n, "ip2psFifo_V_last_V_empty_n");
    sc_trace(mVcdFile, start_for_core_U0_din, "start_for_core_U0_din");
    sc_trace(mVcdFile, start_for_core_U0_full_n, "start_for_core_U0_full_n");
    sc_trace(mVcdFile, start_for_core_U0_dout, "start_for_core_U0_dout");
    sc_trace(mVcdFile, start_for_core_U0_empty_n, "start_for_core_U0_empty_n");
    sc_trace(mVcdFile, start_for_ip2ps_fifo_U0_din, "start_for_ip2ps_fifo_U0_din");
    sc_trace(mVcdFile, start_for_ip2ps_fifo_U0_full_n, "start_for_ip2ps_fifo_U0_full_n");
    sc_trace(mVcdFile, start_for_ip2ps_fifo_U0_dout, "start_for_ip2ps_fifo_U0_dout");
    sc_trace(mVcdFile, start_for_ip2ps_fifo_U0_empty_n, "start_for_ip2ps_fifo_U0_empty_n");
    sc_trace(mVcdFile, ip2ps_fifo_U0_start_full_n, "ip2ps_fifo_U0_start_full_n");
    sc_trace(mVcdFile, ip2ps_fifo_U0_start_write, "ip2ps_fifo_U0_start_write");
#endif

    }
    mHdltvinHandle.open("my_ip_hls.hdltvin.dat");
    mHdltvoutHandle.open("my_ip_hls.hdltvout.dat");
}

my_ip_hls::~my_ip_hls() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete ps2ip_fifo_U0;
    delete core_U0;
    delete ip2ps_fifo_U0;
    delete ps2ipFifo_V_data_V_U;
    delete ps2ipFifo_V_strb_V_U;
    delete ps2ipFifo_V_last_V_U;
    delete ip2psFifo_V_data_V_U;
    delete ip2psFifo_V_strb_V_U;
    delete ip2psFifo_V_last_V_U;
    delete start_for_core_U0_U;
    delete start_for_ip2ps_fbkb_U;
}

void my_ip_hls::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void my_ip_hls::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void my_ip_hls::thread_ap_sync_continue() {
    ap_sync_continue = ap_const_logic_0;
}

void my_ip_hls::thread_core_U0_ap_continue() {
    core_U0_ap_continue = ap_const_logic_1;
}

void my_ip_hls::thread_core_U0_ap_start() {
    core_U0_ap_start = start_for_core_U0_empty_n.read();
}

void my_ip_hls::thread_ip2ps_fifo_U0_ap_continue() {
    ip2ps_fifo_U0_ap_continue = ap_const_logic_1;
}

void my_ip_hls::thread_ip2ps_fifo_U0_ap_start() {
    ip2ps_fifo_U0_ap_start = start_for_ip2ps_fifo_U0_empty_n.read();
}

void my_ip_hls::thread_ip2ps_fifo_U0_start_full_n() {
    ip2ps_fifo_U0_start_full_n = ap_const_logic_1;
}

void my_ip_hls::thread_ip2ps_fifo_U0_start_write() {
    ip2ps_fifo_U0_start_write = ap_const_logic_0;
}

void my_ip_hls::thread_masterOut_TDATA() {
    masterOut_TDATA = ip2ps_fifo_U0_masterOut_TDATA.read();
}

void my_ip_hls::thread_masterOut_TLAST() {
    masterOut_TLAST = ip2ps_fifo_U0_masterOut_TLAST.read();
}

void my_ip_hls::thread_masterOut_TSTRB() {
    masterOut_TSTRB = ip2ps_fifo_U0_masterOut_TSTRB.read();
}

void my_ip_hls::thread_masterOut_TVALID() {
    masterOut_TVALID = ip2ps_fifo_U0_masterOut_TVALID.read();
}

void my_ip_hls::thread_ps2ip_fifo_U0_ap_continue() {
    ps2ip_fifo_U0_ap_continue = ap_const_logic_1;
}

void my_ip_hls::thread_ps2ip_fifo_U0_ap_start() {
    ps2ip_fifo_U0_ap_start = ap_const_logic_1;
}

void my_ip_hls::thread_slaveIn_TREADY() {
    slaveIn_TREADY = ps2ip_fifo_U0_slaveIn_TREADY.read();
}

void my_ip_hls::thread_start_for_core_U0_din() {
    start_for_core_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void my_ip_hls::thread_start_for_ip2ps_fifo_U0_din() {
    start_for_ip2ps_fifo_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void my_ip_hls::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"slaveIn_TDATA\" :  \"" << slaveIn_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"slaveIn_TSTRB\" :  \"" << slaveIn_TSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"slaveIn_TLAST\" :  \"" << slaveIn_TLAST.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"masterOut_TDATA\" :  \"" << masterOut_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"masterOut_TSTRB\" :  \"" << masterOut_TSTRB.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"masterOut_TLAST\" :  \"" << masterOut_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"slaveIn_TVALID\" :  \"" << slaveIn_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"slaveIn_TREADY\" :  \"" << slaveIn_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"masterOut_TVALID\" :  \"" << masterOut_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"masterOut_TREADY\" :  \"" << masterOut_TREADY.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

