// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xmy_ip_hls.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XMy_ip_hls_CfgInitialize(XMy_ip_hls *InstancePtr, XMy_ip_hls_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Psaxilite_BaseAddress = ConfigPtr->Psaxilite_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XMy_ip_hls_Set_rule0_V(XMy_ip_hls *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMy_ip_hls_WriteReg(InstancePtr->Psaxilite_BaseAddress, XMY_IP_HLS_PSAXILITE_ADDR_RULE0_V_DATA, Data);
}

u32 XMy_ip_hls_Get_rule0_V(XMy_ip_hls *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMy_ip_hls_ReadReg(InstancePtr->Psaxilite_BaseAddress, XMY_IP_HLS_PSAXILITE_ADDR_RULE0_V_DATA);
    return Data;
}

void XMy_ip_hls_Set_rule1_V(XMy_ip_hls *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMy_ip_hls_WriteReg(InstancePtr->Psaxilite_BaseAddress, XMY_IP_HLS_PSAXILITE_ADDR_RULE1_V_DATA, Data);
}

u32 XMy_ip_hls_Get_rule1_V(XMy_ip_hls *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMy_ip_hls_ReadReg(InstancePtr->Psaxilite_BaseAddress, XMY_IP_HLS_PSAXILITE_ADDR_RULE1_V_DATA);
    return Data;
}

void XMy_ip_hls_Set_rule2_V(XMy_ip_hls *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMy_ip_hls_WriteReg(InstancePtr->Psaxilite_BaseAddress, XMY_IP_HLS_PSAXILITE_ADDR_RULE2_V_DATA, Data);
}

u32 XMy_ip_hls_Get_rule2_V(XMy_ip_hls *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMy_ip_hls_ReadReg(InstancePtr->Psaxilite_BaseAddress, XMY_IP_HLS_PSAXILITE_ADDR_RULE2_V_DATA);
    return Data;
}

u32 XMy_ip_hls_Get_rule0cnt_V(XMy_ip_hls *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMy_ip_hls_ReadReg(InstancePtr->Psaxilite_BaseAddress, XMY_IP_HLS_PSAXILITE_ADDR_RULE0CNT_V_DATA);
    return Data;
}

u32 XMy_ip_hls_Get_rule0cnt_V_vld(XMy_ip_hls *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMy_ip_hls_ReadReg(InstancePtr->Psaxilite_BaseAddress, XMY_IP_HLS_PSAXILITE_ADDR_RULE0CNT_V_CTRL);
    return Data & 0x1;
}

u32 XMy_ip_hls_Get_rule1cnt_V(XMy_ip_hls *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMy_ip_hls_ReadReg(InstancePtr->Psaxilite_BaseAddress, XMY_IP_HLS_PSAXILITE_ADDR_RULE1CNT_V_DATA);
    return Data;
}

u32 XMy_ip_hls_Get_rule1cnt_V_vld(XMy_ip_hls *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMy_ip_hls_ReadReg(InstancePtr->Psaxilite_BaseAddress, XMY_IP_HLS_PSAXILITE_ADDR_RULE1CNT_V_CTRL);
    return Data & 0x1;
}

u32 XMy_ip_hls_Get_rule2cnt_V(XMy_ip_hls *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMy_ip_hls_ReadReg(InstancePtr->Psaxilite_BaseAddress, XMY_IP_HLS_PSAXILITE_ADDR_RULE2CNT_V_DATA);
    return Data;
}

u32 XMy_ip_hls_Get_rule2cnt_V_vld(XMy_ip_hls *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMy_ip_hls_ReadReg(InstancePtr->Psaxilite_BaseAddress, XMY_IP_HLS_PSAXILITE_ADDR_RULE2CNT_V_CTRL);
    return Data & 0x1;
}

